apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-release-image-version
spec:
  baseOSExtensionsContainerImage: ""
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - contents:
          source: data:,%23!%2Fbin%2Fbash%20%20%0A%0Awhile%20true%3B%20do%0A%20%20cat%20%2Fetc%2Fmachine-config-daemon%2Fcurrentconfig%20%7C%20jq%20-c%20%27.metadata.annotations%27%20%7C%20awk%20--field-separator%20%22%2C%7C%7B%7C%7D%7C%3A%7C%5C%22%22%20%27%7Bprint%20%249%22%3D%22%2412%7D%27%20%3E%20%2Fetc%2Fkubernetes%2Fnode-feature-discovery%2Ffeatures.d%2Fnode-version%3B%0A%20%20sleep%201%3B%0Adone
        mode: 484
        overwrite: true
        path: /etc/kubernetes/node-feature-discovery/source.d/node-version.sh
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Add Node Version

          [Service]
          ExecStart=/bin/bash /etc/kubernetes/node-feature-discovery/source.d/node-version.sh

          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: node-version.service
  fips: false
  kernelArguments: null
  kernelType: ""