apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  operand:
    image: >-
      registry.redhat.io/openshift4/ose-node-feature-discovery
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
        featureSources:
          - "local"