---
- name: Validate
  ansible.builtin.include_tasks: 01-validate.yml

- name: Check For Upgrade
  ansible.builtin.include_tasks: 02-check-for-upgrade.yml
  when:
    - ConfigValidated

- name: Pause Pools
  ansible.builtin.include_tasks: 03-pause-machine-config-pools.yml
  vars:
    pausedBool: true
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeAvailable

- name: Apply Labels
  ansible.builtin.include_tasks: 04-apply-mutex-rules-as-labels.yml
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeAvailable
    - TargetPoolsPaused

- name: Update Canary MachineConfigPool
  ansible.builtin.include_tasks: 05-modify-machineconfigpool.yml
  vars:
    setExpressions: true
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeAvailable
    - TargetPoolsPaused
    - MutexRulesApplied

- name: Run Job
  ansible.builtin.include_tasks: 06-execute-jobs.yml
  loop: "{{ targetNodeList }}"
  loop_control:
    extended: true
    loop_var: targetNode
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeReady
    - TargetPoolsPaused
    - MutexRulesApplied
    - MCPUpdated

- name: UnPause
  ansible.builtin.include_tasks: 03-pause-machine-config-pools.yml
  vars:
    pausedBool: false
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeReady
    - TargetPoolsPaused
    - MutexRulesApplied
    - MCPUpdated
    - JobRun

- name: Remove MCP Expressions
  ansible.builtin.include_tasks: 05-modify-machineconfigpool.yml
  vars:
    setExpressions: false
  when:
    - ConfigValidated
    - UpgradabilityChecked
    - UpgradeReady
    - TargetPoolsPaused
    - MutexRulesApplied
    - MCPUpdated
    - JobRun
