# permissions for end users to edit mutexrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mutexrule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-node-upgrade-mutex-operator
    app.kubernetes.io/part-of: openshift-node-upgrade-mutex-operator
    app.kubernetes.io/managed-by: kustomize
  name: mutexrule-editor-role
rules:
- apiGroups:
  - openshift-optional.skrzypek.io
  resources:
  - mutexrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openshift-optional.skrzypek.io
  resources:
  - mutexrules/status
  verbs:
  - get
