# permissions for end users to edit mutextargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mutextarget-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-node-upgrade-mutex-operator
    app.kubernetes.io/part-of: openshift-node-upgrade-mutex-operator
    app.kubernetes.io/managed-by: kustomize
  name: mutextarget-editor-role
rules:
- apiGroups:
  - openshift-optional.skrzypek.io
  resources:
  - mutextargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openshift-optional.skrzypek.io
  resources:
  - mutextargets/status
  verbs:
  - get
