apiVersion: openshift-optional.skrzypek.io/v1alpha1
kind: Mutex
metadata:
  labels:
    app.kubernetes.io/name: mutex
    app.kubernetes.io/instance: mutex-sample
    app.kubernetes.io/part-of: openshift-node-upgrade-mutex-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openshift-node-upgrade-mutex-operator
  name: mutex-sample
spec:
  # TODO(user): Add fields here
