---
- name: Canary Pool Block
  block:
    # Create the Canary Machine Config Pool
    - name: Create Canary Machine Config Pool
      kubernetes.core.k8s:
        state: present
        template: canarymachineconfigpool.yml
      vars:
        resource_name: "{{ _openshift-optional_skrzypek_io_mutex.metadata.name }}"
        resource_namespace: "{{ _openshift-optional_skrzypek_io_mutex.metadata.namespace }}"
        resource_kind: "{{ _openshift-optional_skrzypek_io_mutex.kind }}"
        resource_group: "{{ _openshift-optional_skrzypek_io_mutex.apiVersion | split('/') | first }}"

    # Upon Success, Set Canary Status true
    - name: Report Canary Created
      operator_sdk.util.k8s_status:
        api_version: "openshift-optional.skrzypek.io/v1alpha1"
        kind: Mutex
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
          - type: Canary
            status: "True"
            reason: Created
            message: Canary machine config pool has been created
            lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

  rescue:
    # Upon Failure, Set Canary Status false
    - name: Report Canary Not Created
      operator_sdk.util.k8s_status:
        api_version: "openshift-optional.skrzypek.io/v1alpha1"
        kind: Mutex
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
          - type: Canary
            status: "False"
            reason: FailedCreate
            message: Failed to create canary machine config pool
            lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

  always:
    # Update Control Flow Variable
    - name: Set Canary Machine Config Pool Present
      ansible.builtin.set_fact:
        canary_machine_config_pool_present: "{{ (ansible_failed_result is not defined) | ternary('true', 'false') }}"
