---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mutexrunconfigs.openshift-optional.skrzypek.io
spec:
  group: openshift-optional.skrzypek.io
  names:
    kind: MutexRunConfig
    listKind: MutexRunConfigList
    plural: mutexrunconfigs
    singular: mutexrunconfig
    categories:
    - numo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MutexRunConfig is the Schema for the mutexrunconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MutexRunConfig
            type: object
            properties:
              canary:
                description: 'Information pertaining to the **existing** machineConfigPool in which upgrades can occur'
                type: object
                properties:
                  name:
                    description: 'Name of an existing machineConfigPool not included in any mutexTargets'
                    type: string
              mutexRules:
                description: 'Information pertaining to the **existing** mutexRules'
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: 'Name of an existing mutexRule resource'
                      type: string
                    namespace:
                      description: 'Namespace of an existing mutexRule resource'
                      type: string
              mutexTargets:
                description: 'Information pertaining to the **existing** mutexTargets'
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: 'Name of an existing mutexRule resource'
                      type: string
                    namespace:
                      description: 'Namespace of an existing mutexTarget resource'
                      type: string
          status:
            description: Status defines the observed state of MutexRunConfig
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
